# Etapa 1: build estático
FROM golang:1.22-alpine AS builder
WORKDIR /src

# Dependências mínimas
RUN apk add --no-cache ca-certificates upx

# Copia o código
COPY main.go .

# Compila estático e reduz tamanho do binário
# - CGO desabilitado => binário puro
# -ldflags "-s -w" remove símbolos de debug
# -trimpath remove paths do build
ENV CGO_ENABLED=0
RUN go build -ldflags="-s -w" -trimpath -buildvcs=false -o /out/fullcycle main.go \
    && ls -lh /out/fullcycle \
    && upx --best --lzma /out/fullcycle || true \
    && ls -lh /out/fullcycle

# Etapa 2: imagem final "vazia"
FROM scratch
# Copia apenas o binário
COPY --from=builder /out/fullcycle /fullcycle
# Segurança básica: usuário não-root (opcional)
USER 65532:65532
ENTRYPOINT ["/fullcycle"]
